services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        VITE_API_URL: ${API_URL}
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      args:
        DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE} # MySQL connection string
      - APP_URL=${APP_URL}
      - CORS=*
      - NODE_ENV=production
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
